
this_file_is_unedited: TRUE # This config file does not work as presented.  There are a few additional files
name: Westeros
start_date: 2020-03-01
end_date: 2020-12-31
nsimulations: 100
dt: 0.25
report_location_name: Westeros

spatial_setup:
  census_year: 2020
  base_path: data
  setup_name: westeros
  us_model: FALSE
  modeled_states: 
  - WES
  geoid_len: 6
  geodata: geodata.csv  
  mobility: mobility.csv
  popnodes: pop
  nodenames: geoid  
  include_in_report: include_in_report
  shapefile: geodata/Westeros/Westeros_districts.shp 
  shapefile_name: geodata/Westeros/Westeros_districts.shp
  geoid_params_file: data/geoid-params.csv

# importation: 
#   census_api_key: <insert-api-key> # For use with the tidycensus package
#   travel_dispersion: 3
#   maximum_destinations: Inf
#   dest_type : state
#   dest_country : USA
#   aggregate_to: airport
#   cache_work: TRUE
#   update_case_data: TRUE
#   draw_travel_from_distribution: FALSE
#   print_progress: FALSE
#   travelers_threshold: 5000
#   airport_cluster_distance: 80
#   param_list:
#   incub_mean_log: log(5.89)
#   incub_sd_log: log(1.74)
#   inf_period_nohosp_mean: 15
#   inf_period_nohosp_sd: 5
#   inf_period_hosp_shape: 0.75
#   inf_period_hosp_scale: 5.367
#   p_report_source: [0.05, 0.25]
#   shift_incid_days: -10
#   delta: 1

#seeding: ## If removing the importation, comment out this seeding block
#  method: FolderDraw
#  folder_path: importation/
# 
seeding:  
   method: PoissonDistributed
   lambda_file: data/seeding.csv

seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3 

interventions:
  scenarios:
    - Uncontrolled
    - PhasedControl
  settings:
    Uncontrolled:
      template: ReduceR0
      period_start_date: 2020-03-01
      period_end_date: 2020-12-31
      value:
        distribution: fixed
        value: 0
    LowSocialDist_ph1:
      template: ReduceR0
      period_start_date: 2020-03-10
      period_end_date: 2020-03-18
      value:
        distribution: uniform
        low: 0.16
        high: 0.30
    ModSocialDist_ph2:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-03-25
      value:
        distribution: uniform
        low: 0.53
        high: 0.57
    HighControl_ph3:
      template: ReduceR0
      period_start_date: 2020-03-26
      period_end_date: 2020-05-26
      value:
        distribution: uniform
        low: 0.61
        high: 0.64
    ModControl_ph4:
      template: ReduceR0
      period_start_date: 2020-05-27
      period_end_date: 2020-08-31
      value:
        distribution: uniform
        low: 0.26
        high: 0.37
    PhasedControl:
      template: Stacked
      scenarios:
        - Uncontrolled
        - LowSocialDist_ph1
        - ModSocialDist_ph2
        - HighControl_ph3
        - ModControl_ph4

hospitalization:
  paths:
    output_path: hospitalization
    run_age_adjust: TRUE
  parameters:
    time_hosp: [log(7), 0.3]
    time_disch: [log(11.5), log(1.22)]
    time_ICU: [log(3), 0.3]
    time_ICUdur: [log(8), 0.2]
    time_ventdur: [log(7), 0.2]
    time_vent: [log(1), 0.4]
    p_death: [.01, .005, .0025]
    p_death_names: ["high", "med", "low"]
    p_hosp_inf: [0.1, .05, .025]
    time_onset_death: [2.84, 0.52]

interventions:
  scenarios:
    - Uncontrolled
    - PhasedControl
  settings:
    Uncontrolled:
      template: ReduceR0
      period_start_date: 2020-03-01
      period_end_date: 2020-12-31
      value:
        distribution: fixed
        value: 0
    LowSocialDist_ph1:
      template: ReduceR0
      period_start_date: 2020-03-10
      period_end_date: 2020-03-18
      value:
        distribution: uniform
        low: 0.16
        high: 0.30
    ModSocialDist_ph2:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-03-25
      value:
        distribution: uniform
        low: 0.53
        high: 0.57
    HighControl_ph3:
      template: ReduceR0
      period_start_date: 2020-03-26
      period_end_date: 2020-05-26
      value:
        distribution: uniform
        low: 0.61
        high: 0.64
    ModControl_ph4:
      template: ReduceR0
      period_start_date: 2020-05-27
      period_end_date: 2020-08-31
      value:
        distribution: uniform
        low: 0.26
        high: 0.37
    PhasedControl:
      template: Stacked
      scenarios:
        - Uncontrolled
        - LowSocialDist_ph1
        - ModSocialDist_ph2
        - HighControl_ph3
        - ModControl_ph4

hospitalization:
  paths:
    output_path: hospitalization
    run_age_adjust: TRUE
  parameters:
    time_hosp: [log(7), 0.3]
    time_disch: [log(11.5), log(1.22)]
    time_ICU: [log(3), 0.3]
    time_ICUdur: [log(8), 0.2]
    time_ventdur: [log(7), 0.2]
    time_vent: [log(1), 0.4]
    p_death: [.01, .005, .0025]
    p_death_names: ["high", "med", "low"]
    p_hosp_inf: [0.1, .05, .025]
    time_onset_death: [2.84, 0.52]

report:
  data_settings:
    pop_year: 2020
  plot_settings:
    plot_intervention: FALSE
    parameters_to_display:
      sigma:
        type: seir
        distribution: exp
        formal_name: Incubation Period
        transform: invert
        xlab: Days since symptom onset
      gamma:
        type: seir
        distribution: gamma
        formal_name: Duration of Infectiousness
        transform: invert
        xlab: Days since symptom onset
      time_hosp:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Hospitalization
        xlab: Days since symptom onset
        xlim: [0,100]
      time_disch:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Discharge
        xlab: Days since hospitalization
      time_ICU:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to ICU Admission
        xlab: Days since hospitalization
        xlim: [0,100]
      time_ICUdur:
        type: hospitalization
        distribution: lnormal
        formal_name: Time in ICU
        xlab: Days since ICU admission
        xlim: [0,100]
      time_death:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Death
        xlab: Days since hopitalization
      time_vent:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Ventilation
        xlab: Days since ICU admission
        xlim: [0,100]
  formatting:
    scenario_labels_short: ["Uncontrolled", "PhasedControl"]
    scenario_labels:
      - Uncontrolled
      - Phased Social Distancing and Control
    scenario_descriptions: ["Uncontrolled", "Phased social distancing and control measures"]
    scenario_colors: ["#43A2CA", "#9933FF"] 
    pdeath_labels: ["1% IFR", "0.5% IFR", "0.25% IFR"]
    display_dates: ["2020-05-01", "2020-06-01", "2020-07-01", "2020-08-01", "2020-09-01","2020-10-01", "2020-11-01","2020-12-01","2020-12-31"]
    display_dates2: ["2020-05-01", "2020-07-01", "2020-09-01", "2020-11-01", "2021-12-31"]
